steps:
- id: 'Decrypt secrets required for deployment'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./eagleproject/app.yaml.enc
    - --plaintext-file=./eagleproject/app.yaml
    - --location=global
    - --keyring=origin
    - --key=cloudbuild

- id: 'Decrypt env required for build'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./eagleproject/.envkey.enc
    - --plaintext-file=./eagleproject/.envkey
    - --location=global
    - --keyring=origin
    - --key=cloudbuild

- id: 'Install requirements, collectstatic, run migrations'
  name: 'python:3.8'
  dir: ./eagleproject
  entrypoint: bash
  args:
    - '-c'
    - |
      export ENVKEY=$(cat .envkey)
      python3 -m pip install -r requirements.txt && \
      python3 ./manage.py collectstatic --noinput && \
      python3 ./manage.py migrate

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: ./eagleproject
  entrypoint: gcloud
  args:
    - app
    - deploy
timeout: "1600s"
