steps:
- id: Install cloud_sql_proxy
  name: gcr.io/cloud-builders/wget
  entrypoint: bash
  args:
    - -c
    - wget -O ./cloud_sql_proxy https://storage.googleapis.com/cloudsql-proxy/v1.15/cloud_sql_proxy.linux.386 && chmod +x ./cloud_sql_proxy

- id: 'Decrypt secrets required for deployment'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./eagleproject/app.yaml.enc
    - --plaintext-file=./eagleproject/app.yaml
    - --location=global
    - --keyring=origin
    - --key=cloudbuild

- id: 'Decrypt secrets required for deployment 2'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./eagleproject/reports_worker.yaml.enc
    - --plaintext-file=./eagleproject/reports_worker.yaml
    - --location=global
    - --keyring=origin
    - --key=cloudbuild

- id: 'Decrypt env required for build'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./eagleproject/.envkey.enc
    - --plaintext-file=./eagleproject/.envkey
    - --location=global
    - --keyring=origin
    - --key=cloudbuild

- id: 'Install requirements, collectstatic, run migrations'
  name: 'python:3.8'
  dir: ./eagleproject
  entrypoint: bash
  args:
    - '-c'
    - |
      export ENVKEY=$(cat .envkey)

      # Run CloudSQL Proxy
      ../cloud_sql_proxy \
        -instances="origin-214503:us-west2:ousd-analytics-w" \
        -dir=/cloudsql &
      
      sleep 3 && \
      python3 -m pip install -r requirements.txt && \
      python3 ./manage.py collectstatic --noinput && \
      python3 ./manage.py migrate

- id: 'Deploy the web facing service and worker'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: ./eagleproject
  entrypoint: gcloud
  args:
    - app
    - deploy
    - /workspace/eagleproject/reports_worker.yaml
    - /workspace/eagleproject/app.yaml
timeout: "3200s"
