steps:
- id: 'Decrypt secrets required for deployment'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=./eagleproject/app.yaml.enc
    - --plaintext-file=./eagleproject/app.yaml
    - --location=global
    - --keyring=origin
    - --key=cloudbuild

- id: 'Install requirements, collectstatic, run migrations'
  name: 'python:3.8'
  dir: ./eagleproject
  entrypoint: sh
  args: |
    - '-c'
    - |
      python3 -m pip install -r requirements.txt && \
      python3 ./manage.py collectstatic --noinput && \
      python3 ./manage.py migrate

# - id: 'Install requirements'
#   name: 'python:3.8'
#   dir: ./eagleproject
#   entrypoint: python3
#   args: ['-m', 'pip', 'install', '-r', 'requirements.txt']

# - id: 'Collect static files'
#   name: 'python:3.8'
#   dir: ./eagleproject
#   entrypoint: python3
#   args: ['./manage.py', 'collectstatic', '--noinput']

# - id: 'Run migrations'
#   name: 'python:3.8'
#   dir: ./eagleproject
#   entrypoint: python3
#   args: ['./manage.py', 'migrate']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: ./eagleproject
  args: ['gcloud', 'app', 'deploy']
timeout: "1600s"
