# Generated by Django 3.1.1 on 2020-09-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200918_1709"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugTx",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(db_index=True, max_length=66)),
                ("block_number", models.IntegerField(db_index=True)),
                ("notes", models.TextField()),
                ("data", models.JSONField()),
            ],
        ),
    ]
