# Generated by Django 3.1.1 on 2020-09-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_logpointer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=255)),
                (
                    "event_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "topic_0",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "topic_1",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "topic_2",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("data", models.TextField(blank=True, max_length=256)),
                (
                    "signature",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("method", models.CharField(blank=True, db_index=True, max_length=255)),
                ("block_number", models.IntegerField(db_index=True)),
                ("log_index", models.IntegerField(db_index=True)),
                ("transaction_hash", models.CharField(db_index=True, max_length=255)),
                ("transactionIndex", models.IntegerField(db_index=True)),
            ],
        ),
    ]
