# Generated by Django 3.1.1 on 2020-09-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200922_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-block_number', '-log_index']},
        ),
        migrations.RemoveField(
            model_name='log',
            name='method',
        ),
        migrations.RemoveField(
            model_name='log',
            name='signature',
        ),
    ]
