# Generated by Django 3.1.1 on 2020-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_assetblock_threepoolstrat_holding"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetblock",
            name="aave_holding",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name="assetblock",
            name="compstrat_holding",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name="assetblock",
            name="ora_tok_usd_max",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name="assetblock",
            name="ora_tok_usd_min",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name="assetblock",
            name="vault_holding",
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
    ]
