# Generated by Django 3.1.1 on 2020-10-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20201021_1131"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetblock",
            old_name="aave_holding",
            new_name="aavestrat_holding",
        ),
    ]
