# Generated by Django 3.1.1 on 2020-11-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_block_ousdtransfer_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_data",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="data",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debug_data",
            field=models.JSONField(default={}),
        ),
    ]
