# Generated by Django 3.1.1 on 2020-11-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20201113_1329"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OusdTransfer",
        ),
    ]
