# Generated by Django 3.1.1 on 2020-12-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_transfer_transaction_fkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherscanPointer',
            fields=[
                ('contract', models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False)),
                ('last_block', models.IntegerField(db_index=True)),
            ],
        ),
    ]
