# Generated by Django 3.1.1 on 2020-12-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_create_ogn_staking_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(db_index=True)),
                ('oracle', models.CharField(db_index=True, max_length=42)),
                ('ticker_left', models.CharField(db_index=True, max_length=6)),
                ('ticker_right', models.CharField(db_index=True, max_length=6)),
                ('price', models.DecimalField(decimal_places=18, max_digits=64)),
            ],
        ),
    ]
