# Generated by Django 3.1.1 on 2020-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_create_ogn_staking_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ognstaked',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ognstaked',
            name='rate',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AddField(
            model_name='ognstaked',
            name='staked_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='ognstaked',
            name='tx_hash',
            field=models.CharField(max_length=66),
        ),
    ]
