# Generated by Django 3.1.1 on 2021-01-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_update_ognstaked_20210105_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTokenSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(db_index=True)),
                ('address', models.CharField(db_index=True, max_length=42)),
                ('borrow_rate', models.DecimalField(decimal_places=18, max_digits=64)),
                ('supply_rate', models.DecimalField(decimal_places=18, max_digits=64)),
                ('borrow_apy', models.DecimalField(decimal_places=18, max_digits=64)),
                ('supply_apy', models.DecimalField(decimal_places=18, max_digits=64)),
                ('total_supply', models.DecimalField(decimal_places=18, max_digits=64)),
                ('total_borrows', models.DecimalField(decimal_places=18, max_digits=64)),
                ('exchange_rate_stored', models.DecimalField(decimal_places=18, max_digits=64)),
            ],
            options={
                'unique_together': {('block_number', 'address')},
            },
        ),
    ]
