# Generated by Django 3.1.1 on 2021-01-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ctokensnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ognstaked',
            name='stake_type',
            field=models.IntegerField(default=0),
        ),
    ]
