# Generated by Django 3.1.1 on 2021-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210119_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctokensnapshot',
            name='total_cash',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
            preserve_default=False,
        ),
    ]
