# Generated by Django 3.1.1 on 2021-01-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_log_topic_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaveLendingPoolCoreSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(db_index=True)),
                ('asset', models.CharField(db_index=True, max_length=42)),
                ('borrowing_enabled', models.BooleanField()),
                ('available_liquidity', models.DecimalField(decimal_places=18, max_digits=64)),
                ('total_liquidity', models.DecimalField(decimal_places=18, max_digits=64)),
                ('current_liquidity_rate', models.DecimalField(decimal_places=27, max_digits=64)),
                ('total_borrows_stable', models.DecimalField(decimal_places=18, max_digits=64)),
                ('total_borrows_variable', models.DecimalField(decimal_places=18, max_digits=64)),
                ('variable_borrow_rate', models.DecimalField(decimal_places=27, max_digits=64)),
                ('stable_borrow_rate', models.DecimalField(decimal_places=27, max_digits=64)),
            ],
        ),
    ]
