# Generated by Django 3.1.1 on 2021-01-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_aavelendingpoolcoresnapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aavelendingpoolcoresnapshot',
            unique_together={('block_number', 'asset')},
        ),
    ]
