# Generated by Django 3.1.1 on 2021-01-28 19:00

import datetime
from django.db import migrations, models


def populate_staked_duration(apps, schema_editor):
    OgnStaked = apps.get_model("core", "OgnStaked")
    for staked in OgnStaked.objects.all():
        staked.staked_duration = datetime.timedelta(days=staked.duration)
        staked.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210128_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ognstaked',
            name='staked_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.RunPython(populate_staked_duration),
    ]
