# Generated by Django 3.1.1 on 2021-02-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_ognstaked_staked_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreePoolSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField(db_index=True, unique=True)),
                ('dai_balance', models.DecimalField(decimal_places=18, max_digits=64)),
                ('usdc_balance', models.DecimalField(decimal_places=18, max_digits=64)),
                ('usdt_balance', models.DecimalField(decimal_places=18, max_digits=64)),
                ('initial_a', models.DecimalField(decimal_places=18, max_digits=64)),
                ('future_a', models.DecimalField(decimal_places=18, max_digits=64)),
                ('initial_a_time', models.DateTimeField()),
                ('future_a_time', models.DateTimeField()),
            ],
        ),
    ]
