# Generated by Django 3.1.1 on 2021-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210215_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('block_start', models.IntegerField()),
                ('block_end', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('accounts_analyzed', models.IntegerField()),
                ('accounts_holding_ousd', models.IntegerField()),
                ('accounts_holding_more_than_100_ousd', models.IntegerField()),
                ('new_accounts', models.IntegerField()),
                ('accounts_with_non_rebase_balance_increase', models.IntegerField()),
                ('accounts_with_non_rebase_balance_decrease', models.IntegerField()),
            ],
        ),
    ]
