# Generated by Django 3.2.8 on 2021-10-15 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_analyticsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 6, 47, 20, 343370)),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='status',
            field=models.CharField(default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 6, 47, 20, 343394)),
        ),
    ]
