# Generated by Django 3.2.8 on 2021-10-20 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211015_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_transactions',
            field=models.JSONField(default=dict),
        )
    ]
