# Generated by Django 3.2.8 on 2021-10-21 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20211020_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='transaction_report',
            field=models.JSONField(default=list),
        )
    ]
