# Generated by Django 3.2.8 on 2021-11-10 14:10

import datetime
from django.db import migrations, models

def populate_(apps, schema_editor):
    if schema_editor.connection.vendor.startswith('postgres'):
        schema_editor.execute(
            "UPDATE core_transaction SET to_address=receipt_data->>'to' WHERE receipt_data->>'to' IS NOT NULL;"
        )
        schema_editor.execute(
            "UPDATE core_transaction SET from_address=receipt_data->>'from';"
        )
    else:
        # TODO:
        # should also provide a sqlLite implementation
        raise Exception('This migration is not implemented in sqlLite. Bug domeng to do it')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20211109_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(db_index=True, default='0xinvalid_address', max_length=42),
        ),
        migrations.RunPython(populate_),
    ]
