# Generated by Django 3.2.8 on 2021-11-18 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20211110_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
    ]
