# Generated by Django 3.2.8 on 2022-07-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20211118_1805"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryStakingSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_number",
                    models.IntegerField(db_index=True, unique=True),
                ),
                ("claiming_index", models.IntegerField()),
                ("staking_index", models.IntegerField()),
                ("user_count", models.IntegerField(default=0)),
                (
                    "total_supply",
                    models.DecimalField(decimal_places=18, max_digits=64),
                ),
                (
                    "vault_eth",
                    models.DecimalField(decimal_places=18, max_digits=64),
                ),
                (
                    "vault_ogn",
                    models.DecimalField(decimal_places=18, max_digits=64),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryStake",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx_hash", models.CharField(db_index=True, max_length=66)),
                ("log_index", models.CharField(db_index=True, max_length=66)),
                (
                    "user_address",
                    models.CharField(db_index=True, max_length=42),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18, default=0, max_digits=64
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=64
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.block",
                    ),
                ),
                (
                    "unstake_block",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="story_unstake",
                        to="core.block",
                    ),
                ),
            ],
            options={
                "unique_together": {("block", "log_index")},
            },
        ),
    ]
