# Generated by Django 4.1.1 on 2022-10-31 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_auto_20220709_0707"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetblock",
            name="metastrat_holdings",
            field=models.JSONField(default=dict),
        ),
    ]
