# Generated by Django 4.1.1 on 2022-11-10 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_add_metastrat_holdings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetblock",
            old_name="metastrat_holdings",
            new_name="strat_holdings",
        ),
    ]
