# Generated by Django 4.1.1 on 2023-02-12 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_rename_metastrat_holdings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "date",
                    models.DateField(db_index=True, primary_key=True, serialize=False),
                ),
                ("block_number", models.IntegerField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 12, 12, 33, 26, 701880)
            ),
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 12, 12, 33, 26, 701892)
            ),
        ),
    ]
