# Generated by Django 4.1.1 on 2023-03-07 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_day_subscriber_alter_analyticsreport_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribed",
            field=models.BooleanField(default=False),
        ),
    ]
