# Generated by Django 4.1.1 on 2023-03-07 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_subscriber_unsubscribed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 7, 16, 48, 19, 900290)
            ),
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 7, 16, 48, 19, 900302)
            ),
        ),
    ]
