# Generated by Django 4.1.7 on 2023-04-27 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_subscriber_unsubscribed"),
    ]

    operations = [
        migrations.RenameModel("OusdTransfer", "TokenTransfer"),
        migrations.AddField(
            model_name="tokentransfer",
            name="project",
            field=models.TextField(
                choices=[("OUSD", "OUSD"), ("OETH", "OETH")], default="OUSD"
            ),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="project",
            field=models.TextField(
                choices=[("OUSD", "OUSD"), ("OETH", "OETH")], default="OUSD"
            ),
        ),
        migrations.AddField(
            model_name="assetblock",
            name="project",
            field=models.TextField(
                choices=[("OUSD", "OUSD"), ("OETH", "OETH")], default="OUSD"
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="project",
            field=models.TextField(
                choices=[("OUSD", "OUSD"), ("OETH", "OETH")], default="OUSD"
            ),
        ),
        migrations.AddField(
            model_name="supplysnapshot",
            name="project",
            field=models.TextField(
                choices=[("OUSD", "OUSD"), ("OETH", "OETH")], default="OUSD"
            ),
        ),
    ]
