# Generated by Django 4.1.7 on 2023-05-22 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_add_project_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticsreport",
            name="project",
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="accounts_holding_more_than_dot1_oeth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="accounts_holding_oeth",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="oeth_accounts_analyzed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="oeth_accounts_with_non_rebase_balance_decrease",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="oeth_accounts_with_non_rebase_balance_increase",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="oeth_new_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analyticsreport",
            name="oeth_transaction_report",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 22, 18, 3, 54, 334146)
            ),
        ),
    ]
