# Generated by Django 3.1.1 on 2020-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyCursor',
            fields=[
                ('cursor_id', models.CharField(
                    choices=[('tr', 'Transactions')],
                    max_length=2,
                    primary_key=True,
                    serialize=False
                )),
                ('block_number', models.IntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='notifycursor',
            index=models.Index(
                fields=['cursor_id', 'block_number'],
                name='notify_noti_cursor__c9a9e0_idx'
            ),
        ),
    ]
