# Generated by Django 3.1.1 on 2020-12-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_create_notifycursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycursor',
            name='cursor_id',
            field=models.CharField(choices=[('tx', 'Transactions'), ('tr', 'Transfers')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
