# Generated by Django 3.1.1 on 2021-01-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_add_cursor_id_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeen',
            fields=[
                ('event_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='eventseen',
            index=models.Index(fields=['last_seen'], name='notify_even_last_se_304519_idx'),
        ),
    ]
