# Generated by Django 3.1.1 on 2021-01-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_add_cursor_id_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycursor',
            name='cursor_id',
            field=models.CharField(choices=[('tx', 'Transactions'), ('tr', 'Transfers'), ('sn', 'Snapshots')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
