# Generated by Django 3.1.1 on 2021-01-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20210105_1441'),
        ('notify', '0003_create_event_seen'),
    ]

    operations = [
    ]
