# Generated by Django 4.1.7 on 2023-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0004_merge_20210107_0704"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifycursor",
            name="project",
            field=models.TextField(
                choices=[("ousd", "ousd"), ("oeth", "oeth")], default="ousd"
            ),
        ),
    ]
